### ISSUE TITLE
Documentation on web seems patchy, and I cannot generate ocamldoc from sources

### ISSUE THREAD

**Issue by tomjridge** [janestreet/sexplib#12]
The most recent documentation appears to be e.g. at the following url:

https://ocaml.janestreet.com/ocaml-core/111.28.00/doc/sexplib/#Std

However, if I open `Sexplib.Std`, I get a function `sexp_of_int`, which doesn't seem to be listed in the documentation.

Perhaps I am looking in the wrong place? For example, the url is referencing a package `sexplib`, and a module `Std`, but I seem to want the module `Sexplib`, submodule `Std`. Where can I find what is contained in the module `Sexplib`? And the module `Sexplib.Std`?

If I clone the source from github, I can build OK. I then do: `make doc`, and no html files seem to be generated. Is it possible to generate plain ocamldoc (rather than opam-doc)?

**Comment by diml** [comment]
We stopped generating ocamldoc documentation a while ago because it wasn't working well with core libraries. Unfortunately opam-doc doesn't work yet with the latest released OCaml compiler which is required by core libraries so we haven't been able to update the documentation on the website.

For this particular problem I think `opam-doc` is choosing the `Std` module from the `sexplib_num` package instead of the one from `sexplib`, which looks like a bug in opam-doc.

If you want to generate plain ocamldoc you can add this stanza at the end of the _oasis file:

```
Document api
  Title: API reference
  Type: ocamlbuild (0.3)
  Install: true
  InstallDir: $htmldir/api
  BuildTools: ocamldoc
  XOCamlbuildPath: ./
  XOCamlbuildLibraries: sexplib, sexplib_num
```

Then `make doc` should work.

**Comment by tomjridge** [comment]
Thanks! I used your oasis clause to build sexplib (sexplib_num didn't work
for me - ocamldoc complained about multiple modules called Std).

Tom
